spring:
  application:
    name: config-center
  cloud:
    config:
      server:
       git: 
          uri: https://github.com/wangwending/ConfigRepository.git
      label: master
      searchPaths: dev
          
   
server: 
       port: 8888
       
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#   